# BEGIN_KITTY_THEME
# Gruvbox Dark
include current-theme.conf
# END_KITTY_THEME

hide_window_decorations yes
cursor_shape block
shell_integration disabled
font_family Fira Code
background_opacity 0.80
window_border_width 0.5pt
window_padding_width 15