[theme]
theme = "gruvbox-dark"
overrides = { separator = " | ", separator_fg = "#ebdbb2" }

[[block]]
block = "cpu"
interval = 2
format = "cpu: $utilization.eng(w:4)"

[[block]]
block = "temperature"
interval = 5
format = "temp: $average"
chip = "k10temp-pci-00c3"
inputs = ["Tctl"]

[[block]]
block = "memory"
interval = 2
format = "mem: $mem_total_used_percents.eng(w:4)"
format_alt = "swap: $swap_used_percents.eng(w:4)"

[[block]]
block = "amd_gpu"
interval = 2
format = "gpu: $utilization.eng(w:4)"

[[block]]
block = "temperature"
interval = 5
format = "temp: $average"
chip = "amdgpu-pci-2d00"
inputs = ["edge"]


[[block]]
block = "sound"
format = "vol: {$volume.eng(w:2)|muted}"

[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = "$timestamp.datetime(f:'%a %d/%m %I:%M %p')"